name 'gocd-server'
maintainer 'Steven Wade'
maintainer_email 'steven@stevenwade.co.uk'
license 'all_rights'
description 'Installs/Configures template'
long_description 'Installs/Configures template'
version '0.1.5'
depends 'gocd'
